server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Chen9277..
    url: jdbc:mysql://localhost:3306/luntan?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapperLocations: classpath:mapper/*.xml